CREATE TABLE TRANSFORMERS
(
    ID                    BIGINT AUTO_INCREMENT UNIQUE PRIMARY KEY,
    KKS                   CHARACTER VARYING(30) UNIQUE,
    FACTORY_NUMBER        CHARACTER VARYING(20),
    TYPE_TRANSFORMER      CHARACTER VARYING(20)
);

CREATE TABLE TRANSFORMER_CHARACTERISTICS
(
    ID                    BIGINT AUTO_INCREMENT UNIQUE PRIMARY KEY,
    CONNECTION_DIAGRAM    CHARACTER VARYING(20),
    DOWN_CURRENT          DOUBLE PRECISION,
    DOWN_VOLTAGE          DOUBLE PRECISION,
    FREQUENCY             INTEGER,
    IDLE_LOSS             DOUBLE PRECISION,
    MIDDLE_CURRENT        DOUBLE PRECISION,
    MIDDLE_VOLTAGE        DOUBLE PRECISION,
    NO_LOAD_CURRENT       DOUBLE PRECISION,
    NUMBER_PHASES         INTEGER,
    POWER                 INTEGER,
    SHORT_CIRCUIT_LOSS    DOUBLE PRECISION,
    SHORT_CIRCUIT_VOLTAGE DOUBLE PRECISION,
    UP_CURRENT            DOUBLE PRECISION,
    UP_VOLTAGE            DOUBLE PRECISION
);

create table PHYSICAL_CHEMICAL_OIL_ANALYSIS
(
    ID                      BIGINT AUTO_INCREMENT UNIQUE PRIMARY KEY,
    ACID_NUMBER             DOUBLE PRECISION,
    BREAKDOWN_VOLTAGE       DOUBLE PRECISION,
    CLEANLINESS_CLASS       INTEGER,
    DATE_ANALYSIS           DATE,
    DIELECTRIC_LOSS_TANGENT DOUBLE PRECISION,
    FLASH_POINT             DOUBLE PRECISION,
    MOISTURE_CONTENT        DOUBLE PRECISION,
    PROTOCOL_NAME           CHARACTER VARYING(40),
    TRANSFORMER             BIGINT,
    FOREIGN KEY (TRANSFORMER) REFERENCES TRANSFORMERS
);

CREATE TABLE CHROMATOGRAPHIC_OIL_ANALYSIS
(
    ID                 BIGINT AUTO_INCREMENT UNIQUE PRIMARY KEY,
    ACETYLENE_C2H2     INTEGER,
    CARBON_DIOXIDE_CO2 INTEGER,
    CARBON_MONOXIDE_CO INTEGER,
    DATE_ANALYSIS      DATE,
    ETHANE_C2H6        INTEGER,
    ETHYLENE_C2H4      INTEGER,
    HYDROGEN_GAS_H2    INTEGER,
    METHANE_CH4        INTEGER,
    PROTOCOL_NAME      CHARACTER VARYING(40),
    TRANSFORMER        BIGINT,
    FOREIGN KEY (TRANSFORMER) references TRANSFORMERS
);

CREATE TABLE GAS_BOUNDARY_CONCENTRATIONS
(
    TRANSFORMER_VOLTAGE_CLASS CHARACTER VARYING(255) not null primary key,
    ACETYLENE_C2H2            INTEGER,
    CARBON_DIOXIDE_CO2        INTEGER,
    CARBON_MONOXIDE_CO        INTEGER,
    ETHANE_C2H6               INTEGER,
    ETHYLENE_C2H4             INTEGER,
    HYDROGEN_GAS_H2           INTEGER,
    METHANE_CH4               INTEGER
);

INSERT INTO GAS_BOUNDARY_CONCENTRATIONS (TRANSFORMER_VOLTAGE_CLASS,
                                             HYDROGEN_GAS_H2,
                                             METHANE_CH4,
                                             ACETYLENE_C2H2,
                                             ETHYLENE_C2H4,
                                             ETHANE_C2H6,
                                             CARBON_MONOXIDE_CO,
                                             CARBON_DIOXIDE_CO2) VALUES
('BEFORE_750_KV', 100, 100, 10, 100, 50, 500, 2000),
('AFTER_750_KV', 30, 20, 10, 20, 10, 500, 4000);


